import type { ArtifactRef, ArtifactStoredEvent } from '$lib/types';

/**
 * Creates a reactive store for managing artifacts.
 * Artifacts are session-scoped downloadable files generated by tools.
 */
function createArtifactsStore() {
  let artifacts = $state<Map<string, ArtifactRef>>(new Map());

  return {
    /** Get the raw artifacts map */
    get artifacts() { return artifacts; },

    /** Get artifacts as an array (for iteration) */
    get list() { return Array.from(artifacts.values()); },

    /** Get the total count of artifacts */
    get count() { return artifacts.size; },

    /**
     * Check if an artifact exists by ID
     */
    has(id: string): boolean {
      return artifacts.has(id);
    },

    /**
     * Get a specific artifact by ID
     */
    get(id: string): ArtifactRef | undefined {
      return artifacts.get(id);
    },

    /**
     * Add an artifact from an SSE event.
     * If artifact with same ID exists, it will be updated.
     */
    addArtifact(event: ArtifactStoredEvent): void {
      const ref: ArtifactRef = {
        id: event.artifact_id,
        mime_type: event.mime_type,
        size_bytes: event.size_bytes,
        filename: event.filename,
        sha256: null,
        source: event.source
      };
      // Create new Map to trigger reactivity
      const newMap = new Map(artifacts);
      newMap.set(event.artifact_id, ref);
      artifacts = newMap;
    },

    /**
     * Remove an artifact by ID.
     * Returns true if artifact was removed, false if it didn't exist.
     */
    remove(id: string): boolean {
      if (!artifacts.has(id)) {
        return false;
      }
      const newMap = new Map(artifacts);
      newMap.delete(id);
      artifacts = newMap;
      return true;
    },

    /**
     * Clear all artifacts.
     * Called when session is reset.
     */
    clear(): void {
      artifacts = new Map();
    }
  };
}

export const artifactsStore = createArtifactsStore();
