"""Framework-neutral, offline learning-control-plane package.

This package deliberately has no request-path dependency on PenguiFlow. Framework
providers and evaluation backends live behind explicit contracts so an unavailable
control plane cannot interrupt an agent serving a customer.
"""

from .providers.assessment_publisher import InvestigationAssessmentPublisher, MlflowAssessmentPublisher
from .control_plane.control_plane import (
    ActivationReceipt,
    AdvisorySkillCandidate,
    ConfidenceIntervalRequirement,
    DeliveryAuthorization,
    GateDecision,
    JobAuditRecord,
    JobState,
    LearningControlPlane,
    LearningJob,
    MetricConfidenceInterval,
    PromotionPolicy,
    ReviewDecision,
    ReviewQueueItem,
)
from .evaluation.evaluation import (
    EvaluationBackend,
    EvaluationCase,
    EvaluationDataset,
    EvaluationRequest,
    EvaluationVariant,
    LocalEvaluationBackend,
    Metric,
    MetricDirection,
    MetricSpecification,
    MetricSummary,
    PairedCaseResult,
    PairedEvaluationResult,
    PairedMetricValue,
    RunOne,
    VariantCaseResult,
)
from .contracts.evidence import (
    MLFLOW_LINEAGE_SCHEMA_VERSION,
    CompositeEvidenceSink,
    EvidenceContext,
    EvidenceEvent,
    EvidenceSink,
    MlflowEvidenceSink,
    OpenTelemetryEvidenceSink,
)
from .contracts.investigation import (
    INVESTIGATION_TRAJECTORY_SCHEMA_VERSION,
    InvestigationStatus,
    InvestigationTrajectoryV1,
    SourceTraceRef,
)
from .mining.investigation_mining import (
    EvaluationCaseBuilder,
    InvestigationSelection,
    MlflowInvestigationReader,
    MlflowTraceAttachmentStore,
    TraceAttachmentDownloader,
    build_held_out_evaluation_cases,
)
from .providers.investigation_publisher import InvestigationPublisher, MlflowAttachmentPublisher
from .mining.mining import (
    CandidateDrafter,
    CandidateMiner,
    MinedCandidate,
    TraceCohorts,
    TraceLearningRecord,
    TracePattern,
    candidate_from_pattern,
    find_repeated_successful_patterns,
    reserve_later_held_out_cohort,
)
from .integrations.penguiflow.projector import (
    PenguiFlowInvestigationContext,
    PenguiFlowInvestigationProjector,
    PenguiFlowInvestigationPublicationHook,
)
from .control_plane.persistence import PersistedControlPlaneState, SQLiteControlPlaneRepository
from .mining.skill_drafting import (
    DraftedAdvisorySkill,
    DraftValidationPolicy,
    LlmSkillDrafter,
    SkillDraftingProvider,
    build_skill_drafting_prompt,
)
from .evaluation.verification import (
    FINAL_ANSWER_RUBRIC_VERSION,
    VERIFICATION_SCHEMA_VERSION,
    CheckStatus,
    CriterionAssessment,
    FinalAnswerAssessment,
    FinalAnswerRubricV1,
    InvestigationVerification,
    RubricCriterion,
    SafeStepEvidence,
    VerificationCheck,
    score_final_answer,
)
from .control_plane.worker import OfflineEvaluationWorker, WorkerRun

__all__ = [
    "ActivationReceipt",
    "AdvisorySkillCandidate",
    "CheckStatus",
    "CandidateDrafter",
    "CandidateMiner",
    "ConfidenceIntervalRequirement",
    "CompositeEvidenceSink",
    "DeliveryAuthorization",
    "CriterionAssessment",
    "DraftedAdvisorySkill",
    "DraftValidationPolicy",
    "EvidenceContext",
    "EvidenceEvent",
    "EvidenceSink",
    "FINAL_ANSWER_RUBRIC_VERSION",
    "FinalAnswerAssessment",
    "FinalAnswerRubricV1",
    "EvaluationCaseBuilder",
    "EvaluationBackend",
    "EvaluationCase",
    "EvaluationDataset",
    "EvaluationRequest",
    "EvaluationVariant",
    "GateDecision",
    "INVESTIGATION_TRAJECTORY_SCHEMA_VERSION",
    "InvestigationStatus",
    "InvestigationSelection",
    "InvestigationTrajectoryV1",
    "InvestigationPublisher",
    "InvestigationAssessmentPublisher",
    "InvestigationVerification",
    "JobState",
    "JobAuditRecord",
    "LearningControlPlane",
    "LearningJob",
    "LocalEvaluationBackend",
    "LlmSkillDrafter",
    "MLFLOW_LINEAGE_SCHEMA_VERSION",
    "MlflowEvidenceSink",
    "MlflowAttachmentPublisher",
    "MlflowAssessmentPublisher",
    "MlflowInvestigationReader",
    "MlflowTraceAttachmentStore",
    "OpenTelemetryEvidenceSink",
    "OfflineEvaluationWorker",
    "Metric",
    "MetricConfidenceInterval",
    "MetricDirection",
    "MetricSpecification",
    "MetricSummary",
    "MinedCandidate",
    "PairedCaseResult",
    "PairedEvaluationResult",
    "PairedMetricValue",
    "PromotionPolicy",
    "PersistedControlPlaneState",
    "PenguiFlowInvestigationContext",
    "PenguiFlowInvestigationProjector",
    "PenguiFlowInvestigationPublicationHook",
    "ReviewDecision",
    "ReviewQueueItem",
    "RunOne",
    "RubricCriterion",
    "SafeStepEvidence",
    "SQLiteControlPlaneRepository",
    "SourceTraceRef",
    "SkillDraftingProvider",
    "TraceCohorts",
    "TraceAttachmentDownloader",
    "TraceLearningRecord",
    "TracePattern",
    "VariantCaseResult",
    "VERIFICATION_SCHEMA_VERSION",
    "VerificationCheck",
    "WorkerRun",
    "candidate_from_pattern",
    "build_skill_drafting_prompt",
    "build_held_out_evaluation_cases",
    "find_repeated_successful_patterns",
    "reserve_later_held_out_cohort",
    "score_final_answer",
]
