name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: astral-sh/setup-uv@v2
      - name: Create virtual environment
        run: uv venv
      - name: Install dependencies
        run: uv pip install -e .[dev]
      - name: Ruff
        run: uv run ruff check .
      - name: Mypy
        run: uv run mypy
      - name: Pytest with coverage
        run: |
          uv run pytest --cov=penguiflow --cov-report=term --cov-report=xml --cov-fail-under=85
      - name: Upload coverage reports
        if: matrix.python-version == '3.12'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
