name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: astral-sh/setup-uv@v2
      - name: Install dependencies
        run: uv pip install -e .[dev]
      - name: Ruff
        run: uv run ruff check .
      - name: Mypy
        run: uv run mypy .
      - name: Pytest
        run: uv run pytest -q
